name: "fetch"
model_name: "Fetch"
usd_path: "${ASSET_PATH}/models/fetch/usd/fetch.usda"
urdf_path: "${ASSET_PATH}/models/fetch/urdf/fetch.urdf"
scale: 1.0

features:
  manipulation:
    enabled: true
    grasping_mode: "physical"
    grasping_direction: "lower"
    disable_grasp_handling: false
    arms:
      - name: "default"
        joints: ["shoulder_pan_joint", "shoulder_lift_joint", "upperarm_roll_joint", 
                "elbow_flex_joint", "forearm_roll_joint", "wrist_flex_joint", "wrist_roll_joint"]
        links: ["shoulder_pan_link", "shoulder_lift_link", "upperarm_roll_link",
               "elbow_flex_link", "forearm_roll_link", "wrist_flex_link", "wrist_roll_link"]
        eef_link: "eef_link"
        finger_links: ["r_gripper_finger_link", "l_gripper_finger_link"]
        finger_joints: ["r_gripper_finger_joint", "l_gripper_finger_joint"]
        workspace_range: [-45, 45]  # in degrees, will be converted to radians
        default_poses:
          vertical: [-0.94121, -0.64134, 1.55186, 1.65672, -0.93218, 1.53416, 2.14474]
          diagonal15: [-0.95587, -0.34778, 1.46388, 1.47821, -0.93813, 1.4587, 1.9939]
          diagonal30: [-1.06595, -0.22184, 1.53448, 1.46076, -0.84995, 1.36904, 1.90996]
          diagonal45: [-1.11479, -0.0685, 1.5696, 1.37304, -0.74273, 1.3983, 1.79618]
          horizontal: [-1.43016, 0.20965, 1.86816, 1.77576, -0.27289, 1.31715, 2.01226]

  locomotion:
    enabled: true
    type: "two_wheel"
    base_footprint_link: "base_footprint"
    base_joints: ["l_wheel_joint", "r_wheel_joint"]
    floor_touching_links: ["l_wheel_link", "r_wheel_link"]
    non_floor_touching_links: ["base_footprint"]
    wheel_radius: 0.0613
    wheel_axle_length: 0.372

  trunk:
    enabled: true
    joints: ["torso_lift_joint"]
    links: ["torso_lift_link"]

  camera:
    enabled: true
    joints: ["head_pan_joint", "head_tilt_joint"]

controllers:
  base:
    name: "DifferentialDriveController"
    control_freq: 30
    motor_type: "velocity"
    control_limits:
      position: [-inf, inf]
      velocity: [-20, 20]
      effort: [-200, 200]

  trunk:
    name: "JointController"
    control_freq: 30
    motor_type: "position"
    control_limits:
      position: [0, 0.4]
      velocity: [-1.5, 1.5]
      effort: [-1000, 1000]
    command_output_limits: null
    use_delta_commands: true

  camera:
    name: "JointController"
    control_freq: 30
    motor_type: "position"
    control_limits:
      position: [-1.57, 1.57]
      velocity: [-3.0, 3.0]
      effort: [-50, 50]
    command_output_limits: null
    use_delta_commands: true

  arm_default:
    name: "InverseKinematicsController"
    control_freq: 30
    command_output_limits: [-0.2, 0.2]
    mode: "pose_delta_ori"
    smoothing_filter_size: 2

  gripper_default:
    name: "MultiFingerGripperController"
    control_freq: 30
    motor_type: "position"
    mode: "binary"
    limit_tolerance: 0.001
    inverted: false

reset_configuration:
  mode: "untuck"
  arm_pose: "vertical"
  joint_positions:
    shoulder_pan_joint: 1.4707963267948965
    shoulder_lift_joint: -0.4
    upperarm_roll_joint: 1.6707963267948966
    elbow_flex_joint: 0.0
    forearm_roll_joint: 1.5707963267948966
    wrist_flex_joint: 0.0
    wrist_roll_joint: 0.0
    r_gripper_finger_joint: 0.05
    l_gripper_finger_joint: 0.05
    torso_lift_joint: 0.02
    head_pan_joint: 0.0
    head_tilt_joint: 1.1707963267948966

proprio_obs:
  enabled_keys:
    - "robot_pos"
    - "robot_ori_cos"
    - "robot_ori_sin"
    - "robot_lin_vel"
    - "robot_ang_vel"
    - "joint_qpos"
    - "joint_qvel"
    - "trunk_qpos"
    - "trunk_qvel"
    - "camera_qpos_sin"
    - "camera_qpos_cos"
    - "eef_default_pos"
    - "eef_default_quat"
    - "grasp_default"
    - "dd_base_lin_vel"
    - "dd_base_ang_vel"

collisions:
  disabled_links:
    - "arm_tool_link"
    - "wrist_ft_link"
    - "wrist_ft_tool_link"
  disabled_pairs:
    - ["shoulder_pan_link", "shoulder_lift_link"]
    - ["shoulder_lift_link", "upperarm_roll_link"]
    - ["upperarm_roll_link", "elbow_flex_link"]
    - ["elbow_flex_link", "forearm_roll_link"]
    - ["forearm_roll_link", "wrist_flex_link"]
    - ["wrist_flex_link", "wrist_roll_link"]
    - ["r_gripper_finger_link", "l_gripper_finger_link"]
