defaults:
  - _self_  # all below configs will override this conf.yaml
  - policy: ???
  - task: ???

policy_name: ???  # filled by policy
headless: true

eval: ??? # filled by policy
log_path: ???

robot:
  type: R1Pro
  controllers:
