defaults:
  - _self_  # all below configs will override this conf.yaml
  - robot: r1pro
  - policy: ???
  - task: ???

policy_name: ???  # filled by policy
headless: true
use_task_info: false

write_video: true 
log_path: ???
