defaults:
  - _self_  # all below configs will override this conf.yaml
  - robot: r1pro
  - task: behavior
  - policy: ???

env_wrapper: 
  _target_: omnigibson.envs.EnvironmentWrapper
policy_name: ???  # filled by policy
headless: true
use_task_info: false
episodes_per_instance: 5  # number of episodes to eval per instance
eval_instance_ids: null  # specific list of instance ids to eval on, if null test on all instances
write_video: true 
max_steps: 1000
log_path: ???
