stages:
  room_object_list:
    foreach:
      - house_single_floor
      - house_double_floor_bottom
      - house_double_floor_top
      - grocery_store_asian
      - grocery_store_cafe
      - grocery_store_convenience
      - hall_arch_wood
      - hall_train_station
      - hall_glass_ceiling
      - hall_conference_large
      - hotel_suite_large
      - hotel_suite_small
      - hotel_gym_spa
      - office_bike
      - office_cubicles_left
      - office_cubicles_right
      - office_large
      - office_vendor_machine
      - restaurant_asian
      - restaurant_cafeteria
      - restaurant_diner
      - restaurant_brunch
      - restaurant_urban
      - restaurant_hotel
      - school_gym
      - school_geography
      - school_biology
      - school_chemistry
      - school_computer_lab_and_infirmary
    do:
      cmd: 'python scripts/batch_3dsmax.py scripts/room_object_list.py -sceneFile cad/scenes/${item}/processed.max -mxsString dir:cad/scenes/${item}/artifacts'
      deps:
      - scripts/room_object_list.py
      # - cad/scenes/${item}/artifacts/sanitycheck.json
      outs:
      - cad/scenes/${item}/artifacts/room_object_list.json
      - cad/scenes/${item}/artifacts/room_object_list.success
  sanitycheck:
    foreach:
      - hotel_suite_small
      - gates_bedroom
    do:
      cmd: 'python scripts/batch_3dsmax.py scripts/new_sanity_check.py -sceneFile cad/scenes/${item}/processed.max -mxsString batch:true -mxsString dir:cad/scenes/${item}/artifacts'
      deps:
      - cad/scenes/${item}/processed.max
      - cad/scenes/${item}/textures
      - scripts/new_sanity_check.py
      outs:
      - cad/scenes/${item}/artifacts/sanitycheck.json
      - cad/scenes/${item}/artifacts/sanitycheck.success
  object_list:
    foreach:
      - public_restroom_futuristic
      - hotel_suite_small
      - gates_bedroom
    do:
      cmd: 'python scripts/batch_3dsmax.py scripts/object_list.py -sceneFile cad/scenes/${item}/processed.max -mxsString dir:cad/scenes/${item}/artifacts'
      deps:
      - scripts/object_list.py
      # - cad/scenes/${item}/artifacts/sanitycheck.json
      outs:
      - cad/scenes/${item}/artifacts/object_list.json
      - cad/scenes/${item}/artifacts/object_list.success
  object_inventory:
    cmd: 'python scripts/object_inventory.py'
    deps:
    - cad/scenes/hotel_suite_small/artifacts/object_list.json
    - cad/scenes/hotel_suite_small/artifacts/object_list.success
    - scripts/object_inventory.py
    outs:
    - artifacts/pipeline/object_inventory.json
    - artifacts/pipeline/object_inventory.success
  export_objs:
    foreach:
      - hotel_suite_small
      - gates_bedroom
    do:
      cmd: 'python scripts/batch_3dsmax.py scripts/export_objs.py -sceneFile cad/scenes/${item}/processed.max -mxsString dir:cad/scenes/${item}/artifacts'
      deps:
      - scripts/export_objs.py
      # - cad/scenes/${item}/artifacts/object_list.success
      # - cad/scenes/${item}/artifacts/sanitycheck.success
      outs:
      - cad/scenes/${item}/artifacts/objects
      - cad/scenes/${item}/artifacts/export_objs.json
      - cad/scenes/${item}/artifacts/export_objs.success
  export_scenes:
    foreach:
      - hotel_suite_small
      - gates_bedroom
    do:
      cmd: 'python scripts/export_scene.py ${item}'
      deps:
      # - cad/scenes/${item}/artifacts/export_objs.success
      # - cad/scenes/${item}/artifacts/objects
      - scripts/export_scene.py
      outs:
      - artifacts/scenes/${item}
