name: Check DVC push

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-dvc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: x64

      - name: Install DVC
        run: pip install dvc[gs]===3.42.0
        
      - name: Authenticate on Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
      - name: Check that the important stages are pullable
        run: dvc pull object_inventory object_inventory_future combined_room_object_list combined_room_object_list_future combined_file_manifest

      # dvc status returns empty dict JSON if everything is up to date. check that using jq.
      - name: Check the status of the stages
        run: |
          python b1k_pipeline/check_dvc_stage_current.py object_inventory
          python b1k_pipeline/check_dvc_stage_current.py object_inventory_future
          python b1k_pipeline/check_dvc_stage_current.py combined_room_object_list
          python b1k_pipeline/check_dvc_stage_current.py combined_room_object_list_future
          python b1k_pipeline/check_dvc_stage_current.py combined_file_manifest
