name: Check DVC push

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-dvc:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: x64

      - name: Install DVC
        run: pip install dvc[gs]
        
      - name: Authenticate on Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
      - name: Check that the object_inventory.json file is pullable.
        run: dvc pull artifacts/pipeline/object_inventory.json
