name: Check DVC push

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-dvc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: x64

      - name: Install DVC
        run: pip install dvc[gs]
        
      - name: Authenticate on Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
      - name: Check that the object_inventory.json file is pullable.
        run: dvc pull artifacts/pipeline/object_inventory.json

      # dvc status returns empty dict JSON if everything is up to date. check that using jq.
      - name: Check the status of the object inventory target
        run: |
          dvc status --json object_inventory | tee /dev/tty | jq -e '. == {}'
