# @package _global_

policy_name: dummy 
log_path: /home/svl/Documents/logs/dummy

model:
  _target_: omnigibson.learning.policies.DummyPolicy

headless: false
robot:
  type: R1Pro
  controllers:
    arm_left: 
      name: InverseKinematicsController
      mode: pose_delta_ori
    arm_right:
      name: InverseKinematicsController
      mode: pose_delta_ori
    trunk:
      name: JointController
      pos_kp: 150
      use_delta_commands: True