# @package _global_

env: omnigibson
policy_name: pi0 
log_path: /svl/u/ravenh/b1k_baselines/OmniGibson/logs/pi0

module:
  _target_: omnigibson.learning.policies.OpenPi
  host: 10.79.12.59
  port: 8000
  text_prompt: pick up the trash
  control_mode: receeding_temporal

robot:
  type: R1Pro
  controllers: