# @package _global_

env: omnigibson
policy_name: openvla 
module:
  _target_: omnigibson.learning.policies.OpenVLA

eval:
  _target_: omnigibson.learning.policies.OpenVLA.load

robot:
  type: R1Pro
  controllers:
    arm_left: 
      name: InverseKinematicsController
      mode: pose_delta_ori
    arm_right:
      name: InverseKinematicsController
      mode: pose_delta_ori
    trunk:
      name: JointController
      pos_kp: 150
      use_delta_commands: True