# @package _global_

policy_name: openvla 
log_path: /home/evans/logs/b1k_baselines/OmniGibson/logs/openvla

model:
  _target_: omnigibson.learning.policies.OpenVLA
  host: 0.0.0.0
  port: 8777
  text_prompt: pick up the trash
  control_mode: receeding_temporal