# @package _global_

policy_name: va
log_path: /home/svl/Documents/logs/va
headless: false

model:
  _target_: omnigibson.learning.policies.VisionActionILPolicy
  use_websocket: true
  host: 0.0.0.0
  port: 8000
  deployed_action_steps: 8
  obs_window_size: 2
  obs_output_size: 
    left_wrist: [120, 120]
    right_wrist: [120, 120]
    head: [180, 180]